default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: 'password1'
  pool: 5

development:
  <<: *default
  database: sam_mgt_development

test:
  <<: *default
  database: sam_mgt_test
